// Generated by scripts/fetch-project-meta.mjs — do not edit by hand.
//
// Fallback for chain metadata that fails to load. Public IPFS gateways
// rate-limit the home page's burst of one metadata fetch per card, and the
// reader reports that as `null` rather than an error, which would otherwise
// render a card as a bare `v2:<id>` with no cover. Chain data still wins.

export type ProjectMeta = {
  name: string | null
  description: string | null
  displayUri: string | null
  thumbnailUri: string | null
}

export const PROJECT_META: Record<string, ProjectMeta> = {
  "v2:1163": {
    "name": "Distortion City #01",
    "description": "An audiovisual work from Jinyao Lin. It generates distorted harmonic with algorithm. Sound is generated with visual and presents diversity in a distorion city.",
    "displayUri": "ipfs://QmTR356BiZDDh7wU6toeHfehuRPrqP3aFpfEu8q9E5eUWg",
    "thumbnailUri": "ipfs://QmPQxKUW9quVum9XFJHE3WZD7VYPaToQ7rekdH9ipQfCiV"
  },
  "v2:1413": {
    "name": "Distortion City #02",
    "description": "An audiovisual work from Jinyao Lin. It generates distorted harmonic with algorithm. Sound is generated with visual as well. It presents diversity in a distorion city.",
    "displayUri": "ipfs://QmWgU5Y9RpTY4CCoeAEmJhGnxtvbaKJR39fHVYxRvxycCA",
    "thumbnailUri": "ipfs://QmWovqmVDxr3pZkpwz3JMTMtx4jXMesri6mRobV4JrVpRE"
  },
  "v2:1586": {
    "name": "Distortion City #03",
    "description": "An audiovisual work from Jinyao Lin. It generates distorted harmonic with algorithm. Sound is generated with visual as well. It presents diversity in a distorion city. You could play all series together to build your own city.",
    "displayUri": "ipfs://QmYCTMRr9BEFB5aKmpbvYHGyJHeKmRCNGoC4ucbbcCB9PV",
    "thumbnailUri": "ipfs://QmTU6cQxbRx6X6HpjvuD6o1E6jEBLihfoGMr7dSaME12a2"
  },
  "v2:1893": {
    "name": "Distortion City #04",
    "description": "An audiovisual work from Jinyao Lin. It generates distorted harmonic with algorithm. Sound is generated with visual as well. It presents diversity in a distorion city. You could play all series together to build your own city.",
    "displayUri": "ipfs://QmTVjUWAUMQc8AVMsw83QhBMxaNbQN8pbKuTKzLJxj6xFU",
    "thumbnailUri": "ipfs://QmRfje31bDQfNv1hshH3P1x9E48tvtNNB9MGBSErLyz4jU"
  },
  "v2:2423": {
    "name": "improviser",
    "description": "This is an audiovisual work from Jinyao Lin. It start with a random gear machine, and it turns into an improviser if you click on it. It start to simulate a musician and play fun. There are totally 10 color styles, 7 kinds of music mood, and infinity combination of gears which also compose the music.",
    "displayUri": "ipfs://QmSn7bb4RRuczJjDvrXhfCZae1meBQBQgP5CHStmdBnW26",
    "thumbnailUri": "ipfs://QmWg1NQfTGWbZHwieK1yqD9bnEBWFbJcMbRiZzuhkXccas"
  },
  "v2:3358": {
    "name": "EvilBeanVerse aka EBV",
    "description": "Each Evil Bean is generated by the same code but made uniquely. There are 6 types of group: class, school, street, block, village and town with different civilization and 10 races.",
    "displayUri": "ipfs://QmePvjFifWtm69TQsLNrXWsXsNTAMTVBFFucuunbitwRbD",
    "thumbnailUri": "ipfs://Qme7LQ6auWjrJnqB62QUaZM8MNmFNgqYkzNyjbX8Hyse6i"
  },
  "v2:3843": {
    "name": "Alley",
    "description": "Staying in the little alley.\nNarrow view, but enough.\n\nAlley by Jinyao Lin (@jinyaolin)\nThis artwork was created using p5js.",
    "displayUri": "ipfs://Qmdkj7jmVjUCWqMF4hXVrswa1UPadDUDZzj5bYwtzYnN7t",
    "thumbnailUri": "ipfs://QmWJoLSDxcyiFj8EXFNaM8HK1MLjKnyn7XYtM9SFQRz1rU"
  },
  "v2:3924": {
    "name": "Distortion City #05",
    "description": "An audiovisual work from Jinyao Lin. It generates distorted harmonic with algorithm. Sound is generated with visual as well. It presents diversity in a distorion city. You could play all series together to build your own city.",
    "displayUri": "ipfs://QmRErAUfaYeisLJEJnKuGbzEeKvNS1N3QFaJZfvgoQQUSn",
    "thumbnailUri": "ipfs://QmTt5yPG6HjUYtT3Vfs3uqAL6B8CUWsC9qFvqEAmtEM4Lx"
  },
  "v2:4068": {
    "name": "Distortion City Tool",
    "description": "This is the tool I created for Distortion City series. Click to draw the shape, toggle line and adjust the fxrand() (rnd and basement) to see how they distorted. Shift + click on the line to add points, shift + click on the point to delete the point. Save Json if you want to use in your program. This is not artwork but because all Distortion City Series stay at fxhash, I share here. ",
    "displayUri": "ipfs://QmbgSQemhEf9H7EtLnh7eBHCmomiHhHRzvD7kHrBJ8qgEb",
    "thumbnailUri": "ipfs://QmXLM646sDLZ7yDFWUxhBQ2M7cbSKWC4iPFuwT9EzGFJ4n"
  },
  "v2:4788": {
    "name": "forsaken",
    "description": "sometimes we forget the world.\nsometime the world forgets us.\nanyway, I have myself.\n\nforsaken by Jinyao Lin (@jinyaolin)\nThis artwork was created using p5js.",
    "displayUri": "ipfs://QmWPT4EoL8keQhYopwTgtZu47b6gmyjARQe6BPVZhxbqkH",
    "thumbnailUri": "ipfs://QmbDuyRXdBwq2PxsRxZCPzubPN468sV3Vbwdjx9E1zXhbf"
  },
  "v2:5651": {
    "name": "reveal",
    "description": "reveal your fortune by the oracle of the unknown.\nperfect is great. glitch makes it perfect.\n\nreveal by Jinyao Lin (@jinyaolin)\n\nThis artwork is written by Jinyao Lin using p5js and gpujs.",
    "displayUri": "ipfs://QmaXhPnYgVsK1YjGCG23kwZKAYgMNQWZgFtNeaxWdpfLkH",
    "thumbnailUri": "ipfs://QmQoqJ24hArNitXEtGNP74daHXdsmtGeZ39YxxQBgTUrVe"
  },
  "v2:6496": {
    "name": "evangel",
    "description": "I wish I am on your side,\nmy soul takes delight.\n\nevangel by Jinyao Lin (@jinyaolin)\n\nThis artwork is written by Jinyao Lin using p5js and gpujs.",
    "displayUri": "ipfs://QmSRw4yKqmPhGnvBJsvALivt93is3VjsDQStScoLfrjfKL",
    "thumbnailUri": "ipfs://QmPwgzT6uQjusLaFaqDj4iWx8UvEEYm9XjqUwUHVHpzAMF"
  },
  "v2:7892": {
    "name": "aura",
    "description": "aura stands still, never fades,\nin the progress of seeking.\n\naura by Jinyao Lin (@jinyaolin)\n\nThis artwork is written by Jinyao Lin using P5JS, THREEJS and GPUJS.",
    "displayUri": "ipfs://QmauaHfiSqFPshERptCTuQR4hBkSJGc4cEUA3tzEZFnPSh",
    "thumbnailUri": "ipfs://QmUYvbZmRbnziB15nQmNUFhrpwod59J8HMpzk1dCeRgybb"
  },
  "v2:10165": {
    "name": "Cloud Atlas",
    "description": "something behind chaos and order.\n\nCloud Atlas by Jinyao Lin (@jinyaolin)\n\nThis artwork is written by Jinyao Lin using P5JS.",
    "displayUri": "ipfs://QmaKkk1xAxGwDFCDWP9WS4dM91XnKin4Z2VXJp23SWrK4x",
    "thumbnailUri": "ipfs://QmbZ32tJzbuaQPzvvYUFugmb9ZEpgfkL9cQqAzYTF5K1kk"
  },
  "v2:11024": {
    "name": "Requiem: Cloud",
    "description": "<Requiem: Cloud> is a gen art project created by Jinyao Lin using p5js.\n\nThere are 103 color sets, 3 frame, 4 fragment and 2 dyeing types. \n",
    "displayUri": "ipfs://QmNURkoFWmkPYAH1Lqiy61w88M3z84nFDteFq1sAjPsPPB",
    "thumbnailUri": "ipfs://Qmc9WrX87eaDXpKqYMxyUNwAez51VAqh9sr4CjNfjRdcTp"
  },
  "v2:13458": {
    "name": "Mythologic",
    "description": "\"Mythologic\" is part of the fxhash interactive minting experience at The Ever-Evolving World of Art, Art Basel Hong-Kong, 2022.\n\nMythologic is a project derived from cloud series, Cloud Atlas and Requiem: Cloud on fxhash. In the series, lines and circles are used in an organics movement like Cloud Hands, which is a move of Tai Chi. Practitioners move their hands slowly and smoothly, make circles and rotate with extreme concentrating. In Chinese we said “floating clouds and flowing water” to describe calligraphers’ freely flowing style of writing. Chi is a very important for oriental artists, and for genart as well. In the series, lines and circles start from one position to another, and develop with organic rotations and movements, like practicing Tai Chi on the canvas. \n\nMythologic was inspired from “Classic of Mountains and Seas”, also known as Shan Hai Jing, is a Chinese classic text and a compilation of mythic geography and beasts. \n\n“There is a beast that looks like a fox with nine tails.” \n“Huangbei: it is a beetle with meat like a tadpole, but with a head and a tail” \n“The beast has the body of a fish but the wings of a bird” \n\nThere are many incredible creatures in the text which describe the oriental fantasy. The idea of Mythologic is to present an illustrated handbook with random generated paintings, each one is like a framed badge, to memorize the glorious age. It uses the \"cloud hands\" technique in every parts of this piece, the center, the circle and the frame. They are all the same algorithm but perform variety with different density and components. Gold, Silver, Copper, Jade and Ruby colors as noble symbol of treasure in Chinese culture. \n\nThis project use p5js. \n\nPress 'S' to save pictures.\n\nThanks to the support of Yi-Wen Lin in this project.",
    "displayUri": "ipfs://QmYnV1oiaGpLq22qbXauYj1ebMsUWmn1QNjeRFikRwncFv",
    "thumbnailUri": "ipfs://QmPe4g7CcacNEwSGAsxs297sYZqqxMSMXJjKxN7tZsgnqD"
  },
  "v2:22357": {
    "name": "Intimate",
    "description": "Intimacy is a beguiling thing,\nElusive and hard to define.\nIt is the close and personal bond\nBetween two hearts intertwined.\n\nIt has its shadows,\nDistortions lead to pain.\nCodependency and lack of boundaries,\nPossessiveness and control, all the same.\n\nNavigating the delicate balance of intimacy\nIs a philosophical pursuit,\nRequiring self-awareness and consideration\nTo nurture healthy, fulfilling roots.\n\nFor beneath the surface of every connection,\nLies a layer of memory and history,\nHiding, waiting, to be uncovered\nAnd reveal the true depth of intimacy.\n\nIntimate is a generative audiovisual project that creates audio and visual elements in real time. It is an experimental project in collaboration with KEF and Parameta on fxhash that minters will meet the artist in person and live-mint together in the KEF Music Gallery designed to showcase high-fidelity sound. This immersive experience allows participants to explore the concept of intimacy and its relationship to the artist and collectors.\n\nClick on the canvas to start generative audiovisual.\n\nThis work uses p5js, webpd, and glfx.",
    "displayUri": "ipfs://QmTunJmVcb5rtAY2XGg69V3cyfFQR1N6qx7y26mJ3SP2Wn",
    "thumbnailUri": "ipfs://QmSLEHtmzkZgDnE8YULpcrx58H9XH51rtM2vnCxGBV8pK1"
  }
}
